#!/bin/bash
jupyter serverextension enable --py jupyterlab_s3_browser
wget -O ~/FirefoxSetup.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64" -P /tmp
tar xjf ~/FirefoxSetup.tar.bz2 -C /srv/repo
ln -s /srv/repo/firefox /usr/lib/firefox/firefox