name: UpdateMembers

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Nightly at midnight

jobs:
  update-members:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Enable Pip Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/.github/scripts/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python --version
          pip install -r .github/scripts/requirements.txt
      - id: 'update_worksheet'
        uses: jroehl/gsheet.action@release # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: 1KUYomxvwUNAVoZrCvdTeIFm9jKe7l_g1Uv9bDLTH6wQ
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getData", "args": { "range": "A:A,C:C" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: dump results
        env:
          #  the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
          GITHUB_TOKEN: ${{ github.token }}

        run: |
          echo $RESULTS > results.json
          python addMembers.py